### ISSUE TITLE
Declare product the patch is designed for

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/PatchCreator#10]
We need to be able to find all e.g. EXM patches and with current implementation it is not possible. The patch creator must add [EXM] prefix to the repository description and embed `<!-- SCEXM --!>` to master readme file.

**Comment by olegburov** [comment]
@AlenPelin @RomanChernyk let's discuss the format of XML-comments in the README file and define the list of tags. 

I think we should add only one tag in a repository's description.

For example:
- `[EXM]: Abstractions for compatible patches and customization`
- `[WFFM]: Fix Audio captcha issue for Web Forms`

While using the XML-comment we can add as many as we need.

For example:
- `[xDB], [ExperienceAnalytics]`
- `[xM], [ContentSearch] `
- `[xM], [MVC]`

**Comment by AlenPelin** [comment]
It is very rare case when more than 1 module used, in most cases it is only platform or platform + module. Prefix in my opinion must be the same as in NuGet packages (currently CMS, EXM, WFFM, SPIF, SA[zure]). 
I suggest to use old OnTime bug report format without colon: `[EXM] Abstractions for compatible patches and customization`
In XML comments I propose either to use the same thing or add a prefix e.g. SC to distinct from description. So either
* `<!-- EXM -->`, or
* `<!-- SCEXM -->`

**Comment by RomanChernyk** [comment]
>ExperienceAnalytics, ContentSearch, MVC don't represent modules, just components within platform so I don't think we need them.

We do need them. The original idea is to separate patches by functionality so that later the correspondent product team could re-use the patches in they product.

While we have different teams working on Core, List Manager, Marketing Foundation, etc., we do need the patches for these feature to be separated.

**Comment by AlenPelin** [comment]
Okay, what if we do reverse thing? Each patch repo is built for given bug ID. The bug ticket already contains everything we need. What if we just add a link to TFS ticket to given github repo?

**Comment by RomanChernyk** [comment]
As for the patches covering different areas at the same time - sometimes this is the case, e.g. List Manager+ExM or different areas of the Platforms, so, I would say a few tags assigned to the patch is a valid case, and they should be both in the description and as XML comments.

**Comment by RomanChernyk** [comment]
>Okay, what if we do reverse thing? Each patch repo is built for given bug ID. The bug ticket already contains everything we need. What if we just add a link to TFS ticket to given github repo?

Nice idea! However, in this case there should be some indication in the TFS ticket saying that the patch is avaialble and referenced by the link. And it should be easily used for filtering.

Probably, tags in TFS?

**Comment by AlenPelin** [comment]
I am not a pro in TFS, so the question to experts.

**Comment by RomanChernyk** [comment]
This seems to require a manual work by engineers to add the link to the GitHub repo + the appropriate tag (e.g. "PSS Patch"), right?

We may need to automate this so that this is not missed. And it might be even possible :) similar to how OnTime works when updating the Support Time Spent field.

**Comment by AlenPelin** [comment]
We can automate this, but I'd prefer to delegate it to somebody who either knows how to do that, or have time to figure out.

**Comment by AlenPelin** [comment]
For now I can propose extra message in the release draft:

5. Go to TFS 12345 and assign these tags: EXM, ListManager

**Comment by RomanChernyk** [comment]
>delegate it to somebody who either knows how to do that, or have time to figure out.
I have an idea to involve some engineer as a 'developer' to the project to work with our backlog.

>Go to TFS 12345 and assign these tags: EXM, ListManager
TFS 12345 is already in the appropriate pool, so no need to assign such kind of tags. Instead, it should be something like "PSS Patch" or "PSS Patch Available". Adding the link to the repo might be optional as the repo can be easily found by ID.

Need no to forget about the aggregated patches with several IDs Sitecore.Support.12345.54321

**Comment by AlenPelin** [comment]
> Need no to forget about the aggregated patches with several IDs Sitecore.Support.12345.54321
That's simple. Just use GitHub search by this ID and it will return all mixed patches.

**Comment by AlenPelin** [comment]
> I have an idea to involve some engineer as a 'developer' to the project to work with our backlog next quarter.

I would be glad to help with implementation on Release Daemon side.

**Comment by RomanChernyk** [comment]
>That's simple. Just use GitHub search by this ID and it will return all mixed patches.

I meant that the 5th step should say 'Go to TFS 12345 and 54321' in this case

**Comment by AlenPelin** [comment]
> I meant that the 5th step should say 'Go to TFS 12345 and 54321' in this case

Makes sense.

**Comment by RomanChernyk** [comment]
Ok, so, do we need a backlog item for this?

Unless Oleg has any objections, I think we can notify Alexey about our proposal.

**Comment by AlenPelin** [comment]
Backlog items added:
https://github.com/SitecoreSupport/ReleaseDaemon/issues/25
https://github.com/SitecoreSupport/ReleaseDaemon/issues/26

**Comment by olegburov** [comment]
I like the idea with TFS tag - `PSS Patch` or `PSS Patch Available`.

**Comment by AlenPelin** [comment]
Thanks @olegburov, this part is already implemented as per SitecoreSupport/ReleaseDaemon#25
