### ISSUE TITLE
WFFM earlier than 8.0 is not supported in terms of generating NuGet packages

### ISSUE THREAD

**Issue by RomanChernyk** [SitecoreSupport/PatchCreator#14]
This should be supported.

**Comment by AlenPelin** [comment]
2.3, 2.4, 2.5

**Comment by AlenPelin** [comment]
and https://dev.sitecore.net/Downloads/Sitecore_Media_Framework/2x/Sitecore_Media_Framework_22.aspx

**Comment by AlenPelin** [comment]
Done, please check.
