### ISSUE TITLE
Dialog box is hidden behind the browser window

### ISSUE THREAD

**Issue by RomanChernyk** [SitecoreSupport/PatchCreator#21]
Steps:
1. Open patch creator for Sitecore 8.1.3
2. Try to create a patch for bug 147253
3. Fill the description
4. Click create

**Result:** No dialog box appears on top of all windows. It is hidden behind the browser window.
**Expected Result:** All dialog boxes should appear on top of all other windows

**Comment by RomanChernyk** [comment]
The same happens for Make Sure source tree is not running dialog when creating a new patch

**Comment by AlenPelin** [comment]
@RomanChernyk please test and reopen if still actual.

**Comment by AlenPelin** [comment]
Reopened, still few scenarios are actual.

**Comment by AlenPelin** [comment]
It should have been fixed now.
