### ISSUE TITLE
Add shields analytics to 'Readme'

### ISSUE THREAD

**Issue by SC-AFI** [SitecoreSupport/PatchCreator#24]
Add shields analytics to releases
http://shields.io/

'Readme - All Releases'

Download statistics 'By Release' - was implemented into ReleaseDaemon https://github.com/SitecoreSupport/ReleaseDaemon/issues/23

**Comment by AlenPelin** [comment]
To fix this it is enough to update `template/master` in https://github.com/SitecoreSupport/Readme repository
