### ISSUE TITLE
Add support of already existing patch repository

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/PatchCreator#3]
We need to add support of already existing patch repository:
**A.** when the same branch exists - clone repo, check out the branch and open latest release in browser
**B.** when desired branch doesn't exist - clone repo, create new orphaned branch
**C.** when desired branch doesn't exist - clone repo, create a branch on a top of existing branch the user can choose from

**Comment by RomanChernyk** [comment]
PatchCreator should also create a publish profile for selected Sitecore instance when cloning existing or new branch.

**Comment by RomanChernyk** [comment]
Please also ensure PatchCreator removes old nuget references and adds new.
This is important as it is usually not clear how to properly reference new nugets.

**Comment by RomanChernyk** [comment]
Additionally, please fix the following issues:
#20 #21 #22

**Comment by AlenPelin** [comment]
There are two sub-tasks:
1. Update CMS packages
2. Update module packages

**Comment by AlenPelin** [comment]
Ensure that for all 3 cases (A, B, C) necessary NuGet packages are generated by PatchCreator.
