### ISSUE TITLE
Start using GitHub Topics

### ISSUE THREAD

**Issue by olegburov** [SitecoreSupport/PatchCreator#39]
@AlenPelin @RomanChernyk @SC-AFI GitHub has introduced a new feature recently - [Topics](https://github.com/blog/2309-introducing-topics).

Let's start using it to tag our repositories. It should help make it easy to search through all patches that we have out there.

Since *Topics* available globally, I would suggest to mark all repositories with the following default topics:

- `sitecore`
- `patch`

And then add topic(s) based on the area a patch fixes. For example:

- `content-search`
- `solr`

Here is an example of some repositories that I already marked:
https://github.com/SitecoreSupport?utf8=%E2%9C%93&q=Solr&type=&language=

Let me know what you thing so that I can update our Readme guidelines.

**Comment by AlenPelin** [comment]
I don't see benefits of "sitecore" and "patch" topics as 99.9% repositories are sitecore patches. 

As for component-related topics, it can be handy, but not really necessary. We have PSS Patch Available tag in TFS and can use TFS search to achieve same thing.

**Comment by AlenPelin** [comment]
Due to our limited resources, I'd prefer to focus on the absolutely required things.

**Comment by AlenPelin** [comment]
@olegburov If you like, you can contribute to PatchCreator - just open PR to add this function.

**Comment by olegburov** [comment]
> I don't see benefits of "sitecore" and "patch" topics as 99.9% repositories are sitecore patches.

@AlenPelin If you do a search globally let say using `topic:solr`, GitHub will return a result from all organizations and individual accounts. To narrow it down to our patches you can either go to SitecoreSupport organization and search from there or add the `sitecore` topic in addition to `solr` one. Like this `topic:sitecore solr`.

I think you right - the `patch` topic is redundant in this case.

**Comment by AlenPelin** [comment]
I understand that it will make possible searching like that. I don't see how it will improve our everyday life :) I mean I don't need to be able to search for solr patches on GitHub. If I really need to do that, I always can search via TFS.

**Comment by olegburov** [comment]
You can, but customers can't. This will help make customer's everyday life easy :)

**Comment by AlenPelin** [comment]
If customers have problems with Solr they should report them via support portal. I don't see any use of searching all patches for Solr on GitHub as all they can find is just bug ID and name (which is not always very descriptive). And if they find something similar to their problem, they are not allowed to install the patch without approval from PSS, check our disclaimer:

### Important Notes

* The patch should be installed only if recommended by Sitecore Support.
* Any related issues and other feedback should be reported via support portal, check KB 654910 for details.
* Check KB 077333 to find more information about Sitecore Patches.
Github Releases(by Release)

**Comment by RomanChernyk** [comment]
If we can automate this, let's leave it in the pool and take over when resources allow. Otherwise, I don't feel like adding this as one more manual step for our engineers.
