### ISSUE TITLE
Change to repo's name to 'Patch.<ID>'.

### ISSUE THREAD

**Issue by olegburov** [SitecoreSupport/PatchCreator#40]
@AlenPelin @RomanChernyk @SC-AFI Currently we're using repo naming template as `Sitecore.Support.<ID>`, which duplicates our organization name on GitHub - `SitecoreSupport`. As a result, the URLs looks like:

- https://github.com/SitecoreSupport/Sitecore.Support.123456

And issue's description comes as `Sitecore.Support.123456`.

What if we change the template to `Patch.<ID>` or `Patch-<ID>`? It will make URLs and descriptions look better:

- https://github.com/SitecoreSupport/Patch.123456
- https://github.com/SitecoreSupport/Patch-123456

In the `README.MD`, an issue's title would be `Sitecore Patch <ID>` or just `Patch <ID>` or `Patch #<ID>`

For example:
![image](https://cloud.githubusercontent.com/assets/2487951/24311251/9238a8d0-1090-11e7-855c-bd173924f5f1.png)

**Comment by AlenPelin** [comment]
Hi @olegburov 

We already had similar discussion some time ago and decided that it is easier to keep it as is. In addition, it is easier to match Sitecore.Support.123456.dll with its sitecoresupport/Sitecore.Support.123456 repository name i.e. you don't need to change URL, just append assembly name.

**Comment by RomanChernyk** [comment]
Hi Guys,

Please also keep in mind that our repo does not always contain patches. Sometimes there are some features that should not be called `patch`.

**Comment by olegburov** [comment]
@AlenPelin we had, but there were just you and me. Now we have more opinions here :)

We can do next:

- For patches, use repo name as `Patch.<ID>` and assembly name as `Sitecore.Patch.<ID>`
- For features/extensions/diagnostics/etc, use repo name as `Sitecore.Support.<ID>` and assembly name as `Sitecore.Support.<ID>`

If you don't see benefits or think it will make things more complicated, then let's keep it as is.

**Comment by AlenPelin** [comment]
Agreed.
