### ISSUE TITLE
Add full support of modules

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/PatchCreator#7]
In certain cases branch name and associated release names should match module version, not CMS version. In this case app should allow to change that manually via writable text box.

**Comment by AlenPelin** [comment]
It was decided to make branch name editable, but in typical scenario it shouldn't be touched. Instead of that, the developer should choose module name and version from combo box:

* No module
* (Detected module no. 1 in selected Sitecore instance)
* ...
* (Detected module no. N in selected Sitecore instance)
* Other module

If module was selected, fill the editable version text box with detected module version. If other module is selected, let developer to fill it in. Use this information to create branch name according to https://github.com/SitecoreSupport/Readme/issues/8

**Comment by AlenPelin** [comment]
@RomanChernyk does it match to what we agreed?

**Comment by RomanChernyk** [comment]
Yes, it looks so. However, could you please clarify that you mean by "Use this information to create branch name according to SitecoreSupport/Readme#8"?

**Comment by RomanChernyk** [comment]
It is also now important to let the developer choose whether to add the Sitecore version postfix [-8.2.0] or not when developing the patch for modules.

**Comment by RomanChernyk** [comment]
And possible add an option to add custom postfix like '-lucene' or anything else.
