### ISSUE TITLE
Change .NET framework version to 4.5.2 for 8.2+

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/PatchCreator#8]
The tool must switch .NET framework version to `4.5.2` in `*.csproj` file and to `net452` in `packages.config`.

**Comment by RomanChernyk** [comment]
A workaround is to change framework version manually, BUT, when you do this the new web.config file is added to the project and, unless noticed, can be copied to the Sitecore instance during publishing and then break it.

That seems to be critical.
